project_identifier: flexicontent-cck-for-joomla
api_key: c7157f327965cb5088d62dc5ba5467d5
base_path: 
files:
  - source: /pkg_en-GB.xml
    translation: /pkg_%locale%.xml
    translation_replace:
      en-GB.: 
