project_identifier: flexicontent-cck-for-joomla
api_key: c7157f327965cb5088d62dc5ba5467d5
base_path: 
files:
  - source: /**/en-GB/*.ini
    translation: /**/%locale%/%locale%.%file_name%.ini
  - source: /plugins/editors-xtd/fccat/*.ini
    translation: /plugins/editors-xtd/fccat/%locale%.%file_name%.ini
  - source: /plugins/editors-xtd/fcitem/*.ini
    translation: /plugins/editors-xtd/fcitem/%locale%.%file_name%.ini
  - source: /pkg_en-GB.xml
    translation: /pkg_%locale%.xml
  - source: /plugins/content/flexibreak/*.ini
    translation: /plugins/content/flexibreak/%locale%/%locale%.%file_name%.ini
  - source: /plugins/finder/flexicontent/*.ini
    translation: /plugins/finder/flexicontent/%locale%/%locale%.%file_name%.ini
  - source: /plugins/flexicontent/flexinotify/*.ini
    translation: /plugins/flexicontent/flexinotify/%locale%/%locale%.%file_name%.ini
  - source: /plugins/osmap/com_flexicontent/*.ini
    translation: /plugins/osmap/com_flexicontent/%locale%/%locale%.%file_name%.ini
  - source: /plugins/search/**/*.ini
    translation: /plugins/search/**/%locale%/%locale%.%file_name%.ini
  - source: /plugins/system/**/*.ini
    translation: /plugins/system/**/%locale%/%locale%.%file_name%.ini
  - source: /plugins/flexicontent_fields/**/*.ini
    translation: /plugins/flexicontent_fields/**/%locale%/%locale%.%file_name%.ini
  - source: /modules/**/language/*.ini
    translation: /modules/**/language/%locale%/%locale%.%file_name%.ini
