"project_identifier" : "flexicontent-cck-for-joomla"
"api_key" : "c7157f327965cb5088d62dc5ba5467d5"
"base_path" : ""

files: [
  {
    "source": "/**/en-GB/*.ini",
    "translation": "/**/%locale%/%locale%.%file_name%.ini",
    "translation_replace": {
      "en-GB.": ""
    }
  },
  {
    "source": "/**/en-GB.*.ini",
    "translation": "/**/%locale%.%file_name%.ini",
    "translation_replace": {
      "en-GB.": ""
    }
  },
  {
    "source": "/pkg_en-GB.xml",
    "translation": "/pkg_%locale%.xml",
    "translation_replace": {
      "en-GB.": ""
    }
  }
]
