name: Crowdin Action

on:
  workflow_dispatch:
  
jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Crowdin action
      uses: crowdin/github-action@v1
      with:
        upload_sources: false
        download_translations: true
      env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}